### PR TITLE
maintenance: add "make format" target

### PR DESCRIPTION
**Pull request by lindig**
Add better support to run ocamlformat and to lint opam files.

### CODE REVIEW

**Review by psafont — APPROVED** [review]

**Review by lippirk — DISMISSED** [review]
Did you run `make format`..?

**Comment by lindig** [comment]
To my surprise "make format" yielded no changes - except the small complaint from lint which I fixed.

**Comment by psafont** [comment]
Check that dune-project has formatting enabled:
```
(lang dune 1.11)
(using fmt 1.2 (enabled_for ocaml))
```

**Review by lippirk — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]
I think I was running ocamlformat while writing this code, but we didn't have the make rules at the time.

**Pull request merged**
